version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r build/main.zip build/
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://build/main.zip
      - echo "DONE!!"

env:
  variables:
    LAMBDA_FUNCTION_NAME: "gpt-blog-api-lambda"
